#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeCarColor_Omron
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="YLALC")]
	public partial class ALCDateDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    #endregion
		
		public ALCDateDataContext() : 
				base(global::ChangeCarColor_Omron.Properties.Settings.Default.YLALCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ALCDateDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ALCDateDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ALCDateDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ALCDateDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WBS_link_tag_view> WBS_link_tag_view
		{
			get
			{
				return this.GetTable<WBS_link_tag_view>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WBS_link_tag_view")]
	public partial class WBS_link_tag_view
	{
		
		private string _tag_no;
		
		private string _modl;
		
		private string _chs_no;
		
		private string _spec;
		
		private string _option_code;
		
		private string _colr;
		
		private System.Nullable<System.DateTime> _tag_dttm;
		
		public WBS_link_tag_view()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag_no", DbType="VarChar(8000)")]
		public string tag_no
		{
			get
			{
				return this._tag_no;
			}
			set
			{
				if ((this._tag_no != value))
				{
					this._tag_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modl", DbType="Char(7) NOT NULL", CanBeNull=false)]
		public string modl
		{
			get
			{
				return this._modl;
			}
			set
			{
				if ((this._modl != value))
				{
					this._modl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chs_no", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string chs_no
		{
			get
			{
				return this._chs_no;
			}
			set
			{
				if ((this._chs_no != value))
				{
					this._chs_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_spec", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string spec
		{
			get
			{
				return this._spec;
			}
			set
			{
				if ((this._spec != value))
				{
					this._spec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_option_code", DbType="Char(5)")]
		public string option_code
		{
			get
			{
				return this._option_code;
			}
			set
			{
				if ((this._option_code != value))
				{
					this._option_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colr", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string colr
		{
			get
			{
				return this._colr;
			}
			set
			{
				if ((this._colr != value))
				{
					this._colr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tag_dttm", DbType="DateTime")]
		public System.Nullable<System.DateTime> tag_dttm
		{
			get
			{
				return this._tag_dttm;
			}
			set
			{
				if ((this._tag_dttm != value))
				{
					this._tag_dttm = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
